version: "3"
services:
  react-app:
    image: travel-log-app-travelfrontend
    stdin_open: true
    ports:
      - "3000:3000"
  api-server:
    image: travel-log-app-nodebackend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"